// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stockExchange.proto

package rs.raf.pds.v5.z2.gRPC;

public final class StockExchange {
  private StockExchange() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockDataList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockDataList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_OrderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Trade_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Trade_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TradeListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TradeListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TradeList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TradeList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientStock_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientStock_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientPortfolioRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientPortfolioRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientPortfolio_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientPortfolio_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StockDataByDateTimeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StockDataByDateTimeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AskData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AskData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AskListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AskListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AskList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AskList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BidList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BidList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023stockExchange.proto\"w\n\tStockData\022\016\n\006sy" +
      "mbol\030\001 \001(\t\022\023\n\013companyName\030\002 \001(\t\022\024\n\014curre" +
      "ntPrice\030\003 \001(\001\022\023\n\013priceChange\030\004 \001(\001\022\014\n\004da" +
      "te\030\005 \001(\t\022\014\n\004hour\030\006 \001(\005\"b\n\tOrderData\022\016\n\006s" +
      "ymbol\030\001 \001(\t\022\r\n\005price\030\002 \001(\001\022\020\n\010quantity\030\003" +
      " \001(\005\022\022\n\nisBuyOrder\030\004 \001(\010\022\020\n\010clientId\030\005 \001" +
      "(\t\"+\n\rStockDataList\022\032\n\006stocks\030\001 \003(\0132\n.St" +
      "ockData\")\n\014OrderRequest\022\031\n\005order\030\001 \001(\0132\n" +
      ".OrderData\" \n\rOrderResponse\022\017\n\007success\030\001" +
      " \001(\010\"u\n\005Trade\022\016\n\006symbol\030\001 \001(\t\022\r\n\005price\030\002" +
      " \001(\001\022\020\n\010quantity\030\003 \001(\005\022\025\n\rbuyerClientId\030" +
      "\004 \001(\t\022\026\n\016sellerClientId\030\005 \001(\t\022\014\n\004date\030\006 " +
      "\001(\t\"0\n\020TradeListRequest\022\016\n\006symbol\030\001 \001(\t\022" +
      "\014\n\004date\030\002 \001(\t\"#\n\tTradeList\022\026\n\006trades\030\001 \003" +
      "(\0132\006.Trade\"/\n\013ClientStock\022\016\n\006symbol\030\001 \001(" +
      "\t\022\020\n\010quantity\030\002 \001(\005\"*\n\026ClientPortfolioRe" +
      "quest\022\020\n\010clientId\030\001 \001(\t\"A\n\017ClientPortfol" +
      "io\022\020\n\010clientId\030\001 \001(\t\022\034\n\006stocks\030\002 \003(\0132\014.C" +
      "lientStock\"8\n\032StockDataByDateTimeRequest" +
      "\022\014\n\004date\030\001 \001(\t\022\014\n\004hour\030\002 \001(\005\"\007\n\005Empty\"D\n" +
      "\007AskData\022\016\n\006symbol\030\001 \001(\t\022\020\n\010askPrice\030\002 \001" +
      "(\001\022\027\n\017availableShares\030\003 \001(\005\"D\n\007BidData\022\016" +
      "\n\006symbol\030\001 \001(\t\022\020\n\010bidPrice\030\002 \001(\001\022\027\n\017requ" +
      "estedShares\030\003 \001(\005\"8\n\016AskListRequest\022\016\n\006s" +
      "ymbol\030\001 \001(\t\022\026\n\016numberOfOffers\030\002 \001(\005\"!\n\007A" +
      "skList\022\026\n\004asks\030\001 \003(\0132\010.AskData\"8\n\016BidLis" +
      "tRequest\022\016\n\006symbol\030\001 \001(\t\022\026\n\016numberOfOffe" +
      "rs\030\002 \001(\005\"!\n\007BidList\022\026\n\004bids\030\001 \003(\0132\010.BidD" +
      "ata2\301\003\n\024StockExchangeService\022&\n\014GetStock" +
      "Data\022\006.Empty\032\016.StockDataList\022,\n\013SubmitOr" +
      "der\022\r.OrderRequest\032\016.OrderResponse\022-\n\014Ge" +
      "tTradeList\022\021.TradeListRequest\032\n.TradeLis" +
      "t\022?\n\022GetClientPortfolio\022\027.ClientPortfoli" +
      "oRequest\032\020.ClientPortfolio\022\035\n\013NotifyTrad" +
      "e\022\006.Trade\032\006.Empty\022+\n\027subscribeToTradeUpd" +
      "ates\022\006.Empty\032\006.Trade0\001\022E\n\026GetStockDataBy" +
      "DateTime\022\033.StockDataByDateTimeRequest\032\016." +
      "StockDataList\022\'\n\nGetAskList\022\017.AskListReq" +
      "uest\032\010.AskList\022\'\n\nGetBidList\022\017.BidListRe" +
      "quest\032\010.BidListB\031\n\025rs.raf.pds.v5.z2.gRPC" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_StockData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_StockData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockData_descriptor,
        new java.lang.String[] { "Symbol", "CompanyName", "CurrentPrice", "PriceChange", "Date", "Hour", });
    internal_static_OrderData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_OrderData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderData_descriptor,
        new java.lang.String[] { "Symbol", "Price", "Quantity", "IsBuyOrder", "ClientId", });
    internal_static_StockDataList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_StockDataList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockDataList_descriptor,
        new java.lang.String[] { "Stocks", });
    internal_static_OrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_OrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderRequest_descriptor,
        new java.lang.String[] { "Order", });
    internal_static_OrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_OrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_OrderResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_Trade_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Trade_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Trade_descriptor,
        new java.lang.String[] { "Symbol", "Price", "Quantity", "BuyerClientId", "SellerClientId", "Date", });
    internal_static_TradeListRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_TradeListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TradeListRequest_descriptor,
        new java.lang.String[] { "Symbol", "Date", });
    internal_static_TradeList_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_TradeList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TradeList_descriptor,
        new java.lang.String[] { "Trades", });
    internal_static_ClientStock_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_ClientStock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientStock_descriptor,
        new java.lang.String[] { "Symbol", "Quantity", });
    internal_static_ClientPortfolioRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_ClientPortfolioRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientPortfolioRequest_descriptor,
        new java.lang.String[] { "ClientId", });
    internal_static_ClientPortfolio_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_ClientPortfolio_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientPortfolio_descriptor,
        new java.lang.String[] { "ClientId", "Stocks", });
    internal_static_StockDataByDateTimeRequest_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_StockDataByDateTimeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StockDataByDateTimeRequest_descriptor,
        new java.lang.String[] { "Date", "Hour", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_AskData_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_AskData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AskData_descriptor,
        new java.lang.String[] { "Symbol", "AskPrice", "AvailableShares", });
    internal_static_BidData_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_BidData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidData_descriptor,
        new java.lang.String[] { "Symbol", "BidPrice", "RequestedShares", });
    internal_static_AskListRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_AskListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AskListRequest_descriptor,
        new java.lang.String[] { "Symbol", "NumberOfOffers", });
    internal_static_AskList_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_AskList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AskList_descriptor,
        new java.lang.String[] { "Asks", });
    internal_static_BidListRequest_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_BidListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidListRequest_descriptor,
        new java.lang.String[] { "Symbol", "NumberOfOffers", });
    internal_static_BidList_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_BidList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BidList_descriptor,
        new java.lang.String[] { "Bids", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
